import Config

# Configure your database
config :frestyl, Frestyl.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "frestyl_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :frestyl, FrestylWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: 4000],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "me/jxEPc1UykVpNlsWJfr2L1oDGpIbU2r3IX02kPrrKbywBMpXyOj76hPBSELKy2",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:frestyl, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:frestyl, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :frestyl, FrestylWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r"priv/static/(?!uploads/).*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/frestyl_web/(controllers|live|components)/.*(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :frestyl, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include HEEx debug annotations as HTML comments in rendered markup
  debug_heex_annotations: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false

# config/config.exs (or config/dev.exs, config/prod.exs)

# Media storage configuration
config :frestyl, :storage_type, :local
config :frestyl, :local_storage_path, "priv/static/uploads"

# Maximum file size limits (in bytes)
config :frestyl, :max_file_sizes, %{
  "document" => 20_971_520,  # 20MB
  "audio" => 104_857_600,    # 100MB
  "video" => 524_288_000,    # 500MB
  "image" => 10_485_760      # 10MB
}

# Allowed file extensions
config :frestyl, :allowed_extensions, %{
  "document" => [".pdf", ".docx", ".txt", ".md", ".rtf", ".odt"],
  "audio" => [".mp3", ".wav", ".ogg", ".flac", ".m4a"],
  "video" => [".mp4", ".webm", ".mov", ".avi", ".mkv"],
  "image" => [".jpg", ".jpeg", ".png", ".gif", ".svg", ".webp"]
}

config :stripity_stripe, :debug_requests, true
